[tool.poetry]
name = "LLM4Vuln"
version = "0.1.0"
description = ""
authors = ["x"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
rich = "^14.0.0"
richuru = "^0.1.1"
langchain-openai = "^0.3.18"
faiss-cpu = "^1.8.0"
tiktoken = "^0.9.0"
pytest = "^8.2.2"
replicate = "^1.0.6"
gitpython = "^3.1.43"
requests = "^2.32.3"
bs4 = "^0.0.2"
langchain-ollama = "^0.3.3"
langchain-community = "^0.3.24"
python-dotenv = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "LLM4Vuln"
]
