#!/usr/bin/env python3
"""Embedding-based in-context-learning example retrieval for GRACE.

Reimplements the intent of systems/GRACE/genexample.py (FAISS similarity search
over an independent candidate corpus, hybrid-reranked by code-Jaccard + a
structural-similarity term) using microsoft/codebert-base in place of the
missing local "model/codet5-base" checkpoint referenced there. CodeBERT is
RoBERTa-architecture, matching the RobertaModel class genexample.py actually
loads, and is already used for the same purpose (embedding-based few-shot
retrieval from the train split) by the sibling svd-bench system.

No AST data is available for PrimeVul, so the structural-similarity term uses
the ordered Joern node-type sequence as a proxy, computed from the `node` text
already generated by primevul_to_grace_with_joern.py.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Sequence

import faiss
import Levenshtein
import numpy as np
import torch
from transformers import AutoModel, AutoTokenizer

_TOKEN_RE = re.compile(r"\w+")
_NODE_TYPE_RE = re.compile(r"\btype=([^\s|]+)")


def tokenize(text: str) -> list[str]:
    return _TOKEN_RE.findall(text)


def jaccard(a: str, b: str) -> float:
    set_a, set_b = set(tokenize(a)), set(tokenize(b))
    if not set_a or not set_b:
        return 0.0
    return len(set_a & set_b) / len(set_a | set_b)


def node_type_sequence(node_text: str) -> list[str]:
    """Ordered `type=...` tokens from a Joern node-CSV text block (AST proxy)."""
    return _NODE_TYPE_RE.findall(node_text or "")


def structural_similarity(query_types: list[str], candidate_types: list[str]) -> float:
    if not query_types or not candidate_types:
        return 0.0
    return Levenshtein.seqratio(query_types, candidate_types)


def hybrid_score(query_func: str, query_types: list[str], candidate_func: str, candidate_types: list[str]) -> float:
    return 0.7 * jaccard(query_func, candidate_func) + 0.3 * structural_similarity(query_types, candidate_types)


class CodeEmbedder:
    """Mean-pooled, L2-normalized CodeBERT embeddings for cosine-similarity search."""

    MODEL_NAME = "microsoft/codebert-base"
    MAX_LENGTH = 512

    def __init__(self, device: str | None = None) -> None:
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.tokenizer = AutoTokenizer.from_pretrained(self.MODEL_NAME)
        self.model = AutoModel.from_pretrained(self.MODEL_NAME)
        self.model.to(self.device)
        self.model.eval()

    @torch.no_grad()
    def embed(self, texts: Sequence[str], batch_size: int = 32) -> np.ndarray:
        vectors: list[np.ndarray] = []
        for start in range(0, len(texts), batch_size):
            batch = list(texts[start : start + batch_size])
            encoded = self.tokenizer(
                batch,
                padding=True,
                truncation=True,
                max_length=self.MAX_LENGTH,
                return_tensors="pt",
            ).to(self.device)
            output = self.model(**encoded)
            mask = encoded["attention_mask"].unsqueeze(-1).float()
            summed = (output.last_hidden_state * mask).sum(dim=1)
            counts = mask.sum(dim=1).clamp(min=1e-9)
            pooled = (summed / counts).detach().cpu().numpy().astype("float32")
            vectors.append(pooled)
        result = np.concatenate(vectors, axis=0)
        norms = np.linalg.norm(result, axis=1, keepdims=True)
        norms[norms == 0] = 1.0
        return result / norms


@dataclass
class Candidate:
    pool_id: str
    pair_id: str
    func: str
    node_types: list[str]


class ExampleRetriever:
    """FAISS top-K cosine retrieval over a candidate pool, hybrid-reranked."""

    def __init__(self, embedder: CodeEmbedder, top_k: int = 5) -> None:
        self.embedder = embedder
        self.top_k = top_k
        self.candidates: list[Candidate] = []
        self._index: faiss.Index | None = None

    def build_corpus(self, candidates: list[Candidate], batch_size: int = 32) -> None:
        self.candidates = candidates
        if not candidates:
            self._index = None
            return
        vectors = self.embedder.embed([c.func for c in candidates], batch_size=batch_size)
        index = faiss.IndexFlatIP(vectors.shape[1])
        index.add(vectors)
        self._index = index

    def query_many(
        self,
        queries: Sequence[tuple[str, list[str], set[str], set[str]]],
        batch_size: int = 32,
    ) -> list[Candidate | None]:
        """queries: (func, node_types, exclude_pool_ids, exclude_funcs) tuples.

        exclude_pool_ids excludes candidates by identity (self / own pair-partner).
        exclude_funcs additionally excludes candidates whose *text* exactly matches
        the query's own func or its pair-partner's func -- PrimeVul contains many
        byte-identical functions duplicated across unrelated commits/pair_ids, so
        identity-based exclusion alone isn't sufficient to avoid re-leaking the
        answer through a different pair_id that happens to carry the same text.

        Returns one best Candidate (or None if the pool is empty / fully excluded)
        per query, in order.
        """
        if self._index is None or not self.candidates:
            return [None] * len(queries)

        query_vectors = self.embedder.embed([q[0] for q in queries], batch_size=batch_size)
        max_exclusions = max((len(q[2]) + len(q[3]) for q in queries), default=0)
        k = min(self.top_k + max_exclusions, len(self.candidates))
        _, neighbor_idxs = self._index.search(query_vectors, k)

        results: list[Candidate | None] = []
        for (query_func, query_types, exclude_pool_ids, exclude_funcs), idxs in zip(queries, neighbor_idxs):
            best: Candidate | None = None
            best_score = -1.0
            for idx in idxs:
                if idx < 0:
                    continue
                candidate = self.candidates[idx]
                if candidate.pool_id in exclude_pool_ids:
                    continue
                if candidate.func in exclude_funcs:
                    continue
                score = hybrid_score(query_func, query_types, candidate.func, candidate.node_types)
                if score > best_score:
                    best_score = score
                    best = candidate
            results.append(best)
        return results
